# COSC420: Floyd-Warshall Algorithm Testing
(Justin Ventura)

In [97]:
# Imprort libraries:
import numpy as np

# Set up test
V = [1, 2, 3, 4]
E = {(0, 2): -2,
     (1, 0): 4,
     (1, 2): 3,
     (2, 3): 2,
     (3, 1): -1}
card_v = len(V) # Cardinality of V
dist = np.zeros((len(V), len(V)))
pred = np.zeros((len(V), len(V)))

# Create the initial cost matrix.
for i in range(card_v):
    for j in range(card_v):
        if (i, j) in E.keys():
            dist[i,j] = E[i,j]
        elif i != j:
            dist[i,j] = np.inf
        if i == j:
            pred[i, j] = np.NaN
        else:
            pred[i, j] = i

# Run the Floyd-Warshall Algorithm.
for k in range(card_v):
    for i in range(card_v):
        for j in range(card_v):
            if dist[i,j] > dist[i,k] + dist[k,j]:
                dist[i,j] = dist[i,k] + dist[k,j]
                pred[i,j] = pred[k,j]

print('D Matrix: \n', dist, end='\n\n')
print('N Matrix: \n', pred, end='\n\n')

D Matrix: 
 [[ 0. -1. -2.  0.]
 [ 4.  0.  2.  4.]
 [ 5.  1.  0.  2.]
 [ 3. -1.  1.  0.]]

N Matrix: 
 [[nan  3.  0.  2.]
 [ 1. nan  0.  2.]
 [ 1.  3. nan  2.]
 [ 1.  3.  0. nan]]



In [100]:
def find_path(D, N, u, v, path):
    """ 
    recursively finds the shortest path from
    the initial u to v, using D and N.
    """
    if u == v:
        print('Path exists!')
    else:
        if N[int(u), int(v)] == np.NaN:
            print('no path found.')
        else:
            path.append(int(N[u,v]))
            return find_path(D, N, u, int(N[u, v]), path)

# Display the shortest path:
find_path(dist, pred, 1, 3, [])
print('Shortest path: ', [p for p in reversed(P)])

Path exists!
Shortest path:  [0, 2, 3]
